[[redirects]]
  from = "/gemini-key"
  to = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key="
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

    X-Content-Type-Options = "nosniff"
